Livesite Schedule
nwplus/CMS-V2 pull request #55
Opened 2020-11-12 01:47 UTC by ianmah

Mostly copied implementation from /[id]/events.js

![image](https://user-images.githubusercontent.com/11839441/98884922-f1065700-2445-11eb-8177-a84c65fe701e.png)
![image](https://user-images.githubusercontent.com/11839441/98884946-fa8fbf00-2445-11eb-9e1e-0312a8a2f2e1.png)

2020-11-14 02:47 UTC, panjenny0 requested changes
Just added some comments regarding the formatting of the timestamps since I think it'd be good to keep them consistent with the other pages. My refactoring of `formatDate` earlier should've fixed the issues with it 😛

2020-11-14 02:47 UTC, panjenny0 commented on pages/Livesite/schedule.js
> +    newEvent.endTime = new Date(newEvent.endTime).toISOString();
```suggestion
    newEvent.startTime = new Date(newEvent.startTime)
    newEvent.endTime = new Date(newEvent.endTime)
```

2020-11-14 02:47 UTC, panjenny0 commented on pages/Livesite/schedule.js
> +        ...newEvent,
I think `startTime` and `endTime` should be formatted here for consistency with the other pages. You probably saw this in events - I basically did `date: formatDate(eventEditing.date, true),`

I think the same should be applied to `handleUpdate`

2020-11-14 02:47 UTC, panjenny0 commented on utility/firebase.js
> +      }
I think `startTime` and `endTime` should be formatted here - I recently refactored the `formatDate` helper so it should work now

2020-11-14 03:09 UTC, ianmah commented
Totally agree with you that we should have consistent dates @panjenny0 however the livesite schedule has already been implemented using ISO date strings and I do not want someone to have to go and refactor the livesite

2020-11-14 04:01 UTC, panjenny0 commented
> Totally agree with you that we should have consistent dates @panjenny0 however the livesite schedule has already been implemented using ISO date strings and I do not want someone to have to go and refactor the livesite

Oh I see, ok! `formatDate` is only changes the timestamp on the frontend though - not sure how this affects livesite?

2020-11-14 04:26 UTC, panjenny0 approved these changes

2020-11-14 22:40 UTC, jackyzha0 commented
Can we change type to be a dropdown?

2020-11-16 00:03 UTC, ianmah commented
![image](https://user-images.githubusercontent.com/11839441/99200759-16ec6e00-275c-11eb-9f0f-11bed452bfca.png)

2020-11-16 00:08 UTC, ianmah commented
![image](https://user-images.githubusercontent.com/11839441/99200871-d17c7080-275c-11eb-8dbb-cb3bfaa16a70.png)

2020-11-16 00:19 UTC, jackyzha0 approved these changes
looks good chief 🧼 🧞

2020-11-16 00:44 UTC, merged